name: Continues Deployment

on:
  push:
    branches: [ Dev ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to EC2_server
      uses: appleboy/ssh-action@master
      with:
        host: 3.108.65.5
        username: ${{ secrets.TARGET_USER }}
        key: ${{ secrets.PRIVATE_KEY }}
        port: 22
        script: |
          cd /develop
          sudo git pull origin Dev
          sudo systemctl  restart apache2
